name:                sudoku
version:             0.1.0.0
github:              "juril33t/sudoku"
license:             BSD3
author:              "Juri Dispan"
maintainer:          "juri.dispan@me.com"
copyright:           "all-rights-reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            misc

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juril33t/sudoku#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4.0

ghc-options:
- -O2
- -Wall  

library:
  source-dirs: src
  dependencies:
  - random >= 1.1
  - random-shuffle >= 0.0.4 

executables:
  sudoku-gen:
    main:                Main.hs
    source-dirs:         app
    #ghc-options:
    #- -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    dependencies:
    - sudoku
    - random >= 1.1

  sudoku-gui:
    main:                Main.hs
    source-dirs:         gui
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
    - threepenny-gui >= 0.8.3.1  

tests:
  sudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
    - hspec
